### ISSUE TITLE
404 not found on mobile

### ISSUE THREAD

**Issue by mrtpcet** [dec0dOS/standard-notes-ultimate-editor#1]
Hello and thanks for your great editor !
I have this error when I try to open a note with your editor :
```
404 Not found
openresty/1.13.6.2
```

I try to disconnect/reconnect my app but it don't change

**Comment by dec0dOS** [comment]
Hello! Please log in on the desktop and click this button.
<img width="353" alt="Screenshot" src="https://user-images.githubusercontent.com/14824142/107339218-78a74480-6acd-11eb-9bbc-9b1aee820124.png">


The editor is available. You could try out it here:
https://raw.githack.com/dec0dOS/standard-notes-ultimate-editor/main/build/index.html

**Comment by dec0dOS** [comment]
The current version lacks documentation. There are plenty of new cool features :)

**Comment by mrtpcet** [comment]
> Hello! Please log in on the desktop and click this button.
> <img alt="Screenshot" width="353" src="https://user-images.githubusercontent.com/14824142/107339218-78a74480-6acd-11eb-9bbc-9b1aee820124.png">
> 
> The editor is available. You could try out it here:
> https://raw.githack.com/dec0dOS/standard-notes-ultimate-editor/main/build/index.html

I try that but I still have the error on my iPhone !

> The current version lacks documentation. There are plenty of new cool features :)

Yeahhh, I can see that !! Thanks !

**Comment by dec0dOS** [comment]
You could uninstall the editor on the desktop, open the SN app on the smartphone, and open random note, install the editor on the desktop and then open the mobile app.  
Editor caching on mobile works strangely.

**Comment by mrtpcet** [comment]
Perfetto !
