### ISSUE TITLE
[Feature request] Non destructive "/" command

### ISSUE THREAD

**Issue by mrtpcet** [dec0dOS/standard-notes-ultimate-editor#3]
Hello and thank you again for your editor which I use every day !!!

My problem is : 

If I have some words in a line and I tape "/" command to insert Todo list, the check square erase my words. 

It is possible he doesn't ? It's pretty annoying with your great command workflow.

Thanks a lot !

**Comment by dec0dOS** [comment]
Hello! Thanks for your constructive feedback! Currently, this made by design by the main dependency that I use.
It may change in near feature, there is the proposal.

As a workaround for now, instead of using the menu to apply the style you can use a markdown shortcut.

**Comment by mrtpcet** [comment]
Thanks for your answer ! I use the markdown shortcut indeed

**Comment by dec0dOS** [comment]
Hey @mrtpcet! Check out the new release! "/" command behavior has been improved.
