### ISSUE TITLE
The keyboard does not disappear on ios

### ISSUE THREAD

**Issue by mrtpcet** [dec0dOS/standard-notes-ultimate-editor#4]
Hi, it's me again!
When I edit a note, I can't find a way to make the keyboard disappear. It's normal ?

**Comment by dec0dOS** [comment]
Hello.
Hiding the keyboard was always the responsibility of the operating system or a keyboard application (on android, for example)
On iPadOS, there is a keyboard hiding button. 
![photo_2021-03-22_22-28-26](https://user-images.githubusercontent.com/14824142/112047345-3823f780-8b5e-11eb-9bb6-829d2b710186.jpg)

Please refer to iOS documentation or look for something like [this](https://apple.stackexchange.com/questions/1938/how-can-i-hide-the-onscreen-keyboard-in-the-ios-messaging-app)

**Comment by mrtpcet** [comment]
Yes i know ! But this is what I see on my iPhone and swipe down don't work. So maybe is not the editor

![IMG_18F32180F796-1](https://user-images.githubusercontent.com/60814449/112047802-02771280-8b4e-11eb-82bc-6bfd4fe180f1.jpeg)

**Comment by dec0dOS** [comment]
I consider that out of scope for the editor itself.
Please refer to iOS documentation.
